#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
爬取一嗨租车全国门店信息
抓包替换请求头cookie
"""
import requests
import json
from urllib.parse import quote
import openpyxl
import pandas as pd
from pyquery import PyQuery as pq
import asyncio
from aiohttp_requests import requests as aio_requests

HEADERS = {
    "Host": "www.1hai.cn",
    "Connection": "keep-alive",
    "Content-Length": "0",
    "Accept": "*/*",
    "Origin": "https://www.1hai.cn",
    "X-Requested-With": "XMLHttpRequest",
    "User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 afari/537.36",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-Mode": "cors",
    "Referer": "https://www.1hai.cn/yyd_beijing/",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "zh-CN,zh;q=0.9",
    "Cookie": "sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%22176b6e6cc8d2d-0f0f2d47dd11c1-5c63397d-2073600-176b6e6cc8e5b%22%2C%22%24device_id%22%3A%22176b6e6cc8d2d-0f0f2d47dd11c1-5c63397d-2073600-176b6e6cc8e5b%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_referrer%22%3A%22%22%2C%22%24latest_referrer_host%22%3A%22%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%7D%7D; ASP.NET_SessionId=ks1o3d5j41iay5swqkq0vniu; ai_user=/NvO/|2021-01-05T10:09:39.659Z"
}

CITIES = [
    "阿克苏",
    "安达",
    "安图",
    "安顺",
    "安庆",
    "安康",
    "安阳",
    "安吉",
    "鞍山",
    "巴彦淖尔",
    "巴中",
    "霸州",
    "白沙",
    "白城",
    "白银",
    "百色",
    "蚌埠",
    "包头",
    "宝鸡",
    "宝应",
    "保亭",
    "保定",
    "保山",
    "北京",
    "北海",
    "本溪",
    "毕节",
    "滨州",
    "沧州",
    "苍溪",
    "昌江",
    "长汀",
    "长临河",
    "长春",
    "长沙",
    "长治",
    "长丰",
    "常熟",
    "常州",
    "常德",
    "常山",
    "巢湖",
    "朝阳",
    "潮州",
    "郴州",
    "成都",
    "承德",
    "澄迈",
    "池州",
    "赤壁",
    "赤峰",
    "滁州",
    "楚雄",
    "慈溪",
    "从江",
    "重庆",
    "达州",
    "大庆",
    "大连",
    "大理",
    "大同",
    "大冶",
    "丹东",
    "丹阳",
    "儋州",
    "德宏",
    "德州",
    "德清",
    "德阳",
    "德兴",
    "德惠",
    "德令哈",
    "定州",
    "定安",
    "定西",
    "东方",
    "东阳",
    "东莞",
    "东营",
    "都匀",
    "敦化",
    "敦煌",
    "鄂州",
    "鄂尔多斯",
    "恩施",
    "防城港",
    "丰城",
    "佛山",
    "扶余",
    "福清",
    "福安",
    "福鼎",
    "福州",
    "抚顺",
    "抚州",
    "阜阳",
    "阜新",
    "富阳 ",
    "赣州",
    "高安",
    "高密",
    "高州",
    "格尔木",
    "公主岭",
    "巩义",
    "共青城",
    "固原",
    "广安",
    "广汉",
    "广元",
    "广州",
    "贵阳",
    "贵港",
    "贵定",
    "桂林",
    "哈尔滨",
    "海安",
    "海口",
    "海宁",
    "海阳",
    "邯郸",
    "汉中",
    "汉川",
    "杭州",
    "合肥",
    "河源",
    "菏泽",
    "贺州",
    "鹤壁",
    "鹤岗",
    "衡水",
    "衡阳",
    "红安",
    "洪洞",
    "侯马",
    "呼和浩特",
    "呼伦贝尔",
    "湖州",
    "葫芦岛",
    "怀化",
    "怀仁",
    "淮北",
    "淮南",
    "淮安",
    "黄山",
    "黄石",
    "黄冈",
    "珲春",
    "会昌",
    "惠州",
    "霍州",
    "鸡西",
    "吉首",
    "吉水",
    "吉安",
    "吉林",
    "济南",
    "济宁",
    "佳木斯",
    "嘉兴",
    "嘉峪关",
    "简阳",
    "建德",
    "建瓯",
    "剑阁",
    "江山",
    "江油",
    "江门",
    "江阴",
    "焦作",
    "蛟河",
    "揭阳",
    "介休",
    "金昌",
    "金华",
    "锦州",
    "进贤",
    "晋中",
    "晋城",
    "缙云",
    "荆州",
    "荆门",
    "景德镇",
    "靖江",
    "九江",
    "酒泉",
    "句容 ",
    "喀什",
    "开封",
    "开化",
    "凯里",
    "库尔勒",
    "昆明",
    "昆山",
    "拉萨",
    "来宾",
    "莱西",
    "兰溪",
    "兰州",
    "廊坊",
    "阆中",
    "乐山",
    "乐清",
    "乐东",
    "耒阳",
    "醴陵",
    "丽水",
    "丽江",
    "利川",
    "溧阳",
    "连云港",
    "廉江",
    "辽阳",
    "聊城",
    "林芝",
    "临沂",
    "临汾",
    "临高",
    "临海",
    "灵宝",
    "灵石",
    "陵水",
    "浏阳",
    "柳州",
    "六安",
    "六盘水",
    "龙岩",
    "龙游",
    "龙泉",
    "陇南",
    "娄底",
    "泸州",
    "吕梁",
    "洛阳",
    "漯河",
    "麻城",
    "马鞍山",
    "茂名",
    "眉山",
    "梅州",
    "蒙自",
    "汨罗",
    "绵阳",
    "牡丹江",
    "内江",
    "南部",
    "南昌",
    "南京",
    "南通",
    "南宁",
    "南充",
    "南阳",
    "南平",
    "宁德",
    "宁波",
    "宁海 ",
    "栖霞",
    "祁东",
    "祁县",
    "齐齐哈尔",
    "启东",
    "千岛湖",
    "潜江",
    "钦州",
    "秦皇岛",
    "青岛",
    "青州",
    "清远",
    "庆阳",
    "庆元",
    "琼中",
    "琼海",
    "曲靖",
    "曲阜",
    "衢州",
    "泉州",
    "仁怀",
    "日照",
    "荣成",
    "如皋",
    "瑞金",
    "瑞昌",
    "瑞安",
    "三门峡",
    "三明",
    "三亚",
    "三穗",
    "三江",
    "汕头",
    "汕尾",
    "商丘",
    "上海",
    "上饶",
    "尚志",
    "韶关",
    "邵阳",
    "邵武",
    "绍兴",
    "深圳",
    "沈阳",
    "十堰",
    "石家庄",
    "双峰",
    "朔州",
    "四平",
    "四会",
    "泗阳",
    "松阳",
    "松原",
    "苏州",
    "宿迁",
    "宿州",
    "绥芬河",
    "随州",
    "遂宁",
    "遂溪",
    "遂昌",
    "台山",
    "台州",
    "太仓",
    "太原",
    "太谷",
    "泰和",
    "泰州",
    "泰安",
    "唐山",
    "腾冲",
    "天津",
    "天水",
    "铁岭",
    "通辽",
    "通化",
    "桐庐",
    "铜陵",
    "铜仁",
    "图们",
    "屯昌 ",
    "万安",
    "万宁",
    "威海",
    "潍坊",
    "渭南",
    "温州",
    "温岭",
    "文山",
    "文昌",
    "闻喜",
    "乌兰察布",
    "乌海",
    "乌鲁木齐",
    "无锡",
    "吴忠",
    "吴川",
    "芜湖",
    "梧州",
    "五指山",
    "武义",
    "武胜",
    "武威",
    "武夷山",
    "武汉",
    "婺源",
    "西昌",
    "西宁",
    "西安",
    "西双版纳",
    "锡林浩特",
    "峡江",
    "厦门",
    "仙桃",
    "咸宁",
    "咸阳",
    "香格里拉",
    "湘潭",
    "襄阳",
    "襄汾",
    "孝感",
    "忻州",
    "辛集",
    "新化",
    "新干",
    "新郑",
    "新乡",
    "新余",
    "信阳",
    "兴义",
    "兴国",
    "兴宁",
    "邢台",
    "雄安新区",
    "徐州",
    "许昌",
    "宣城",
    "雅安",
    "烟台",
    "延安",
    "延吉",
    "盐城",
    "扬州",
    "阳江",
    "阳泉",
    "阳春",
    "阳新",
    "伊春",
    "依兰",
    "宜春",
    "宜宾",
    "宜兴",
    "宜昌",
    "义乌",
    "益阳",
    "银川",
    "应县",
    "英德",
    "鹰潭",
    "营口",
    "永州",
    "永济",
    "永康",
    "永安",
    "永城",
    "于都",
    "余姚",
    "榆林",
    "玉林",
    "玉溪",
    "原平",
    "岳阳",
    "云浮",
    "运城",
    "枣庄",
    "湛江",
    "张家港",
    "张家口",
    "张家界",
    "张掖",
    "漳州",
    "漳浦",
    "樟树",
    "昭通",
    "诏安",
    "肇东",
    "肇庆",
    "镇江",
    "郑州",
    "枝江",
    "中山",
    "中卫",
    "舟山",
    "周口",
    "株洲",
    "珠海",
    "驻马店",
    "资阳",
    "资中",
    "淄博",
    "自贡",
    "遵义 ",
]


def get_city():
    url = "https://www.1hai.cn/City/?from=Nav"
    r = requests.get(url, headers=HEADERS)
    lis = pq(r.text)('div[@class="city-list clearfix"] li')
    city = {}
    for li in lis:
        if 'ErrorPage' not in pq(li)('a').attr('href'):
            city.update({
                pq(li)('a').text(): pq(li)('a').attr('href')
            })
    return city


def get_dist(url):
    resp = requests.get(url, headers=HEADERS)
    dist = []
    div = pq(resp.text)('div[@class="new-area-box"]')
    links = pq(div)('a')
    for link in links:
        dist.append(link.text)
    return dist


async def get_stores(city, dist):
    url = f"https://www.1hai.cn/storeguide/LoadStores.ashx?City={quote(city)}&Dist={quote(dist)}"
    resp = await aio_requests.session.post(url, data='', headers=HEADERS)
    if resp.status == 200:
        body = await resp.read()
        stores = []
        result = json.loads(body.decode('utf-8'))
        stores.extend(result.get('stores') or [])
        return stores
    print(city, dist, '访问失败')
    return []


def write_excel_xlsx(path, sheet_name, value):
    index = len(value)
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = sheet_name
    for i in range(0, index):
        for j in range(0, len(value[i])):
            sheet.cell(row=i + 1, column=j + 1, value=str(value[i][j]))
    workbook.save(path)


def handle_data(city, data_list):
    id_set = set()
    output = []
    for data in data_list:
        id_ = data.get('Id') or ""
        if id_ not in id_set:
            output.append([
                data.get('StoreName') or "",
                data.get('Address') or "",
                data.get('Phone') or "",
                data.get('OpeningHours') or "",
                city + "-" + data.get('District') or "",
                data.get('BaiduLongitude') or "",
                data.get('BaiduLatitude') or "",
            ])
            id_set.add(id_)
    return output


if __name__ == '__main__':
    all_data = []
    all_write_data = []
    cities = get_city()
    write = pd.ExcelWriter('一嗨营业网点.xlsx')
    excel_header = [
        "门店名称",
        "门店地址",
        "门店电话",
        "营业时间",
        "所属区域",
        "百度经度",
        "百度纬度",
    ]
    for city in CITIES:
        # if city in ('晋江',):
        #     continue
        results = []
        url = f"https://www.1hai.cn/StoreGuide.aspx?City={quote(city)}"
        dists = get_dist(url)
        tasks = []
        for dist in dists:
            stores = asyncio.ensure_future(get_stores(city, dist))
            tasks.append(stores)
        loop = asyncio.get_event_loop()
        loop.run_until_complete(asyncio.wait(tasks))
        for t in tasks:
            results.extend(t.result())
        write_data = handle_data(city, results)

        print(city, "========>", write_data)
        # df = pd.DataFrame(write_data)
        # df.to_excel(write, sheet_name=city, header=excel_header, index=False)

        all_data.append({city: results})
        all_write_data.extend(write_data)
    df = pd.DataFrame(all_write_data)
    df.to_excel(write, sheet_name='sheet1', header=excel_header, index=False)

    write.save()
    # with open('datas.json', 'wb') as f:
    #     f.write(json.dumps(all_data, ensure_ascii=False).encode('utf-8'))
